Repository javascript-tutorial/ko.javascript.info, pull requests merged in 2019-10, with the labels that each got.

#240 1-js/02-first-steps/07-operators/article.md 리뷰
  1-js/02-first-steps/07-operators/article.md
Labels: review needed

#243 1-js/02-first-steps/01-hello-world/2-hello-alert-ext/solution.md 오타 수정
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/solution.md
Labels: review needed

#242 1-js/02-first-steps/08-comparison/article.md 리뷰
  1-js/02-first-steps/08-comparison/article.md
Labels: changes requested

#241 1-js/02-first-steps/07-operators/1-increment-order/solution.md 오타 수정
  1-js/02-first-steps/07-operators/1-increment-order/solution.md
Labels: changes requested

#234 #233: 1-js/01-getting-started/1-intro/article.md 2차 리뷰
  1-js/01-getting-started/1-intro/article.md
Labels: changes requested

#239 1-js/02-first-steps/06-type-conversions/article.md 2차 리뷰
  1-js/02-first-steps/06-type-conversions/article.md
Labels: changes requested

#112 1-js/05-data-types/09-keys-values-entries 리뷰
  1-js/05-data-types/09-keys-values-entries/01-sum-salaries/solution.md
  1-js/05-data-types/09-keys-values-entries/01-sum-salaries/task.md
  1-js/05-data-types/09-keys-values-entries/02-count-properties/task.md
  1-js/05-data-types/09-keys-values-entries/article.md
Labels: review needed, under review

#244 intro 2차 리뷰
  1-js/01-getting-started/1-intro/article.md
Labels: changes requested

#259 기초 문법 요약 2차 리뷰
  1-js/02-first-steps/16-javascript-specials/article.md
Labels: needs +1

#260 위크맵 위크셋 리뷰
  1-js/05-data-types/08-weakmap-weakset/article.md
Labels: needs +1

#262 Property descriptor 1차 리뷰
  1-js/07-object-properties/01-property-descriptors/article.md
Labels: review needed

#257 #236 맵과 셋 과제 번역
  1-js/05-data-types/07-map-set/02-filter-anagrams/solution.md
  1-js/05-data-types/07-map-set/03-iterable-keys/solution.md
  1-js/05-data-types/07-map-set/03-iterable-keys/task.md
Labels: review needed

#168 코드 구조 2차 리뷰
  1-js/02-first-steps/02-structure/article.md
Labels: changes requested

#274 헤딩에서 영문 병기 제거
  1-js/06-advanced-functions/07-new-function/article.md
  2-ui/1-document/06-dom-attributes-and-properties/article.md
  2-ui/2-events/01-introduction-browser-events/article.md
  2-ui/2-events/02-bubbling-and-capturing/article.md
  2-ui/2-events/03-event-delegation/article.md
  7-animation/1-bezier-curve/article.md
Labels: review needed

#267 1-js/02-first-steps/14-function-basics 1차 리뷰
  1-js/02-first-steps/14-function-basics/4-pow/task.md
  1-js/02-first-steps/14-function-basics/article.md
Labels: review needed

#255 맵과 셋 리뷰
  1-js/05-data-types/07-map-set/article.md
Labels: review needed

#282 1-js/02-first-steps/10-ifelse/article.md 리뷰
  1-js/02-first-steps/10-ifelse/article.md
Labels: review needed

#283 1-js/11-async/01-callbacks/article.md 띄어쓰기 수정
  1-js/11-async/01-callbacks/article.md
Labels: review needed

#286 #285 [프락시] 과제 번역
  1-js/99-js-misc/01-proxy/03-observable/solution.md
Labels: review needed

#287 #285 [프락시] 과제 1 문제 번역
  1-js/99-js-misc/01-proxy/01-error-nonexisting/solution.md
Labels: review needed

#288 #285 [프락시] 과제 번역
  1-js/99-js-misc/01-proxy/02-array-negative/task.md
Labels: review needed

#292 #285 프락시 과제 3 문제 번역
  1-js/99-js-misc/01-proxy/03-observable/task.md
Labels: review needed

#293 #285 [프락시] 과제 1 문제 번역
  1-js/99-js-misc/01-proxy/03-observable/task.md
Labels: review needed

#295 #285 [프락시] 과제 번역
  1-js/99-js-misc/01-proxy/02-array-negative/solution.md
Labels: review needed

#276 eval 해답 번역 및 수정사항 반영
  1-js/99-js-misc/02-eval/1-eval-calculator/solution.md
Labels: review needed

#222 private, protectd 프로퍼티와 메서드 번역 #153
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: review needed

#253 [수정]1-js\03-code-quality\03-comments 1차 리뷰
  1-js/03-code-quality/03-comments/article.md
Labels: changes requested

#318 eval 번역 및 수정
  1-js/99-js-misc/02-eval/article.md
Labels: review needed

#261 위크맵 위크셋 과제 번역
  1-js/05-data-types/08-weakmap-weakset/01-recipients-read/solution.md
  1-js/05-data-types/08-weakmap-weakset/01-recipients-read/task.md
  1-js/05-data-types/08-weakmap-weakset/02-recipients-when-read/solution.md
  1-js/05-data-types/08-weakmap-weakset/02-recipients-when-read/task.md
Labels: review needed

#320 fix/#230: 참 값은 값과 거짓 같은 값을 truthy, falsy로 수정
  1-js/02-first-steps/10-ifelse/article.md
  1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/solution.md
  1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
  1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/solution.md
  1-js/02-first-steps/11-logical-operators/4-alert-and/solution.md
  1-js/02-first-steps/11-logical-operators/5-alert-and-or/solution.md
  1-js/02-first-steps/11-logical-operators/8-if-question/solution.md
  1-js/02-first-steps/11-logical-operators/article.md
  1-js/02-first-steps/14-function-basics/article.md
Labels: review needed

#249 1-js / 08-prototypes / 04-prototype-methods 초벌 번역
  1-js/08-prototypes/04-prototype-methods/article.md
Labels: review needed

#331 [form-elements/add-select-option] 과제 해답 번역
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/solution.md
Labels: review needed

#329 [Form properties and methods] 과제 번역
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
Labels: review needed

#333 [테스트 자동화와 Mocha] 2차 리뷰
  1-js/03-code-quality/05-testing-mocha/article.md
Labels: review needed

#279 6-data-storage/02-localstorage/article.md 번역
  6-data-storage/02-localstorage/1-form-autosave/task.md
  6-data-storage/02-localstorage/article.md
Labels: changes requested

#332 [코딩 스타일] 2차 리뷰
  1-js/03-code-quality/02-coding-style/article.md
Labels: review needed

#335 [변수와 상수] 과제 해답 보완
  1-js/02-first-steps/04-variables/2-declare-variables/solution.md
  1-js/02-first-steps/04-variables/3-uppercast-constant/solution.md
Labels: review needed

#336 [if문과 조건부 연산자 '?'] 과제 해답 보완
  1-js/02-first-steps/10-ifelse/5-rewrite-if-question/task.md
  1-js/02-first-steps/10-ifelse/6-rewrite-if-else-question/task.md
Labels: review needed

#342 1-js/09-classes/06-instanceof 번역 완료
  1-js/09-classes/06-instanceof/article.md
Labels: changes requested
