Repository javascript-tutorial/ko.javascript.info, pull requests merged in 2019-09, with the labels that each got.

#104 1-js/03-code-quality/01-debugging-chrome/article.md 리뷰
  1-js/03-code-quality/01-debugging-chrome/article.md
Labels: ready to merge

#122 #83 descendant에 대한 번역어 통일
  2-ui/1-document/03-dom-navigation/article.md
  2-ui/1-document/07-modifying-document/article.md
Labels: review needed

#123 #67 method에 대한 번역어 통일
  1-js/06-advanced-functions/03-closure/6-filter-through-function/task.md
  1-js/06-advanced-functions/10-bind/article.md
Labels: review needed

#130 #76 return value에 대한 번역어 통일
  1-js/02-first-steps/07-operators/article.md
  1-js/02-first-steps/08-comparison/article.md
  1-js/02-first-steps/10-ifelse/article.md
  1-js/05-data-types/05-array-methods/article.md
  1-js/06-advanced-functions/02-rest-parameters-spread-operator/article.md
  1-js/06-advanced-functions/03-closure/article.md
Labels: review needed

#132 #73: 불리언 값을 불린값으로 수정
  1-js/02-first-steps/11-logical-operators/article.md
Labels: review needed

#131 #72 primitive에 대한 번역어 통일
  1-js/04-object-basics/05-object-toprimitive/article.md
  1-js/05-data-types/01-primitives-methods/1-string-new-property/solution.md
  1-js/05-data-types/01-primitives-methods/article.md
Labels: review needed

#133 #65 global, local에 대한 번역어 통일
  1-js/06-advanced-functions/03-closure/article.md
Labels: review needed

#138 #135 한 문장에 많은 쉼표 수정
  1-js/02-first-steps/01-hello-world/1-hello-alert/task.md
Labels: review needed

#141 #136 필요없는 heading 없애기
  1-js/08-prototypes/01-prototype-inheritance/article.md
Labels: review needed

#140 1-js/06-advanced-functions/10-bind/article.md 제목 수정
  1-js/06-advanced-functions/10-bind/article.md
Labels: review needed

#145 1-js/01-getting-started/4-devtools/article.md 리뷰
  1-js/01-getting-started/4-devtools/article.md
Labels: review needed

#146 1-js/02-first-steps 번역되지 않은 부분 번역
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/solution.md
  1-js/02-first-steps/07-operators/2-assignment-result/solution.md
Labels: changes requested

#154 Property 번역어 통일
  1-js/10-error-handling/2-custom-errors/article.md
Labels: review needed

#155 1-js/02-first-steps/01-hello-world/article.md 리뷰
  1-js/02-first-steps/01-hello-world/article.md
Labels: changes requested

#161 Property 번역어 통일
  1-js/08-prototypes/01-prototype-inheritance/article.md
  1-js/08-prototypes/02-function-prototype/article.md
Labels: review needed

#163 1-js\01-getting-started\3-code-editors 2차 리뷰
  1-js/01-getting-started/3-code-editors/article.md
Labels: review needed

#165 #162 제너레이터 과제 번역
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/solution.md
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/task.md
Labels: review needed

#196 #174 Copy and sort array 과제 번역
  1-js/05-data-types/05-array-methods/5-copy-sort-array/task.md
Labels: review needed

#199 #174 Translate border-left-width to borderLeftWidth 과제 번역
  .vs/ProjectSettings.json
  .vs/slnx.sqlite
  1-js/05-data-types/05-array-methods/1-camelcase/task.md
  xaa
Labels: changes requested

#201 #172 Check for spam 해답 번역
  1-js/05-data-types/03-string/2-check-spam/solution.md
Labels: review needed

#195 #172 Truncate the text 과제 번역
  1-js/05-data-types/03-string/3-truncate/task.md
Labels: review needed

#185 Create an extendable calculator 과제 번역(#174)
  1-js/05-data-types/05-array-methods/6-calculator-extendable/task.md
Labels: review needed

#184 #173 Bad Style 과제 번역
  1-js/03-code-quality/02-coding-style/1-style-errors/task.md
Labels: review needed

#183 #172 Which values get shown by the for loop? 해답 번역
  1-js/02-first-steps/12-while-for/3-which-value-for/solution.md
Labels: review needed

#181 #172 which values get shown by the for loop? 과제번역
  1-js/02-first-steps/12-while-for/3-which-value-for/task.md
Labels: review needed

#180 #172 Check for spam 해답 번역
  1-js/05-data-types/03-string/2-check-spam/solution.md
Labels: review needed

#171 #68: property를 속성에서 프로퍼티로 수정
  1-js/08-prototypes/02-function-prototype/article.md
  1-js/10-error-handling/2-custom-errors/article.md
Labels: changes requested

#164 ﻿09-alert-prompt-confirm 리뷰
  1-js/02-first-steps/09-alert-prompt-confirm/article.md
Labels: help wanted, review needed

#210 1-js/04-object-basics/06-constructor-new 리뷰
  1-js/04-object-basics/06-constructor-new/article.md
Labels: review needed

#177 [수정완료반영] #110 Curring
  1-js/99-js-misc/03-currying-partials/article.md
Labels: review needed

#220 1-js/01-getting-started/1-intro/article.md 리뷰
  1-js/01-getting-started/1-intro/article.md
Labels: review needed

#166 10-destructuring-assignment 리뷰
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: changes requested

#221 함수 표현식과 화살표 함수 리뷰
  1-js/02-first-steps/15-function-expressions-arrows/article.md
Labels: review needed

#217 1-js/02-first-steps/04-variables/article.md 리뷰
  1-js/02-first-steps/04-variables/article.md
Labels: review needed

#224 eval 과제 번역 및 수정사항 반영
  1-js/99-js-misc/02-eval/1-eval-calculator/task.md
Labels: review needed

#227 기초 문법 요약 리뷰
  1-js/02-first-steps/16-javascript-specials/article.md
Labels: review needed

#229 13-modules_01-modules-intro 리뷰
  1-js/13-modules/01-modules-intro/article.md
Labels: review needed

#231 13-modules_02-iamport-export 리뷰
  1-js/13-modules/02-import-export/article.md
Labels: review needed

#232 13-modules_03-dynamic-imports 리뷰
  1-js/13-modules/03-modules-dynamic-imports/article.md
Labels: review needed
