Repository javascript-tutorial/ko.javascript.info, pull requests merged in 2020-10, with the labels that each got.

#879 #878 [오타수정] 9.2 클래스 상속
  1-js/09-classes/02-class-inheritance/article.md
Labels: review needed

#884 [웹소켓] 번역, line45(#883)
  5-network/11-websocket/article.md
Labels: review needed

#885 [웹소켓] 번역, line31(#883)
  5-network/11-websocket/article.md
Labels: review needed

#886 [웹소켓] 번역, line26(#883)
  5-network/11-websocket/article.md
Labels: review needed

#887 [웹소켓] 번역, line22(#883)
  5-network/11-websocket/article.md
Labels: review needed

#888 [웹소켓] 번역, line1(#883)
  5-network/11-websocket/article.md
Labels: review needed

#890 [웹소켓] 번역, line63 (#883)
  5-network/11-websocket/article.md
Labels: review needed

#891 [웹소켓] 번역, line9(#883)
  5-network/11-websocket/article.md
Labels: review needed

#892 [웹소켓]번역,line17(#883)
  5-network/11-websocket/article.md
Labels: review needed

#896 [웹소켓] 번역, line29(#883)
  5-network/11-websocket/article.md
Labels: review needed

#897 [웹소켓] 번역, line65(#883)
  5-network/11-websocket/article.md
Labels: review needed

#900 [웹소켓] 번역, line39(#883)
  5-network/11-websocket/article.md
Labels: review needed

#901 [웹소켓] 번역, line15(#883)
  5-network/11-websocket/article.md
Labels: review needed

#902 [웹소켓] 번역, line54(#883)
  5-network/11-websocket/article.md
Labels: review needed

#903 [웹소켓] 번역, line52(#883)
  5-network/11-websocket/article.md
Labels: review needed

#905 [웹소켓] 번역, line33(#883)
  5-network/11-websocket/article.md
Labels: review needed

#907 [웹소켓] 번역, line5(#883)
  5-network/11-websocket/article.md
Labels: review needed

#909 [웹소킷] 번역, line67(#883)
  5-network/11-websocket/article.md
Labels: review needed

#910 [웹소켓] 번역, line69(#883)
  5-network/11-websocket/article.md
Labels: review needed

#911 [웹소켓] 번역, line71(#883)
  5-network/11-websocket/article.md
Labels: review needed

#912 [웹소켓] 번역, line50(#883)
  5-network/11-websocket/article.md
Labels: review needed

#899 [웹소켓] 번역, line40(#883)
  5-network/11-websocket/article.md
Labels: changes requested

#889 [웹소켓] 번역, line53(#883)
  5-network/11-websocket/article.md
Labels: changes requested

#893 [웹소켓] 번역, line18(#883)
  5-network/11-websocket/article.md
Labels: changes requested

#904 [웹소켓] 번역, line28(#883)
  5-network/11-websocket/article.md
Labels: changes requested

#906 [웹소켓] 번역, line25(#883)
  5-network/11-websocket/article.md
Labels: changes requested

#922 line2 번역#920
  5-network/11-websocket/article.md
Labels: hacktoberfest-accepted, review needed

#921 Update Line #20, #67
  5-network/11-websocket/article.md
Labels: hacktoberfest-accepted, review needed

#923 [오번역수정] CONTRIBUTING.md 파일 line26 강조부분 작은 따옴표로 수정
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#918 [오타수정] 제너레이터 본문내 전개 문법 링크 깨짐 #917
  1-js/12-generators-iterators/1-generators/article.md
Labels: review needed

#916 [오타 수정] 파트3 - 7.10 Greedy and lazy quantifiers
  9-regular-expressions/10-regexp-greedy-and-lazy/1-lazy-greedy/task.md
Labels: review needed
