Repository javascript-tutorial/ko.javascript.info, pull requests merged in 2020-06, with the labels that each got.

#560 issue 해결 - 배열과 메서드 과제 보완
  1-js/05-data-types/05-array-methods/2-filter-range/task.md
Labels: review needed

#562 [논리 연산자] || 연산자의 단락평가 수정
  1-js/02-first-steps/11-logical-operators/article.md
Labels: review needed

#566 [private, protected 프로퍼티와 메서드] 읽기 전용 프로퍼티 예제 SyntaxError 수정
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: review needed

#565 [프로퍼티 getter와 setter] 오타 수정
  1-js/07-object-properties/02-property-accessors/article.md
Labels: review needed

#568 [버블링과 캡쳐링] 원문 삭제
  2-ui/2-events/02-bubbling-and-capturing/article.md
Labels: review needed

#574 [프레임과 윈도우] 큰 주제 번역
  3-frames-and-windows/index.md
Labels: review needed

#569 [웹 컴포넌트] 주제 번역
  8-web-components/index.md
Labels: changes requested

#567 [유니코드 클래스] 번역
  9-regular-expressions/03-regexp-unicode/article.md
Labels: review needed, under review

#586 [기본 연산자와 수학] 오타 수정
  1-js/02-first-steps/08-operators/article.md
Labels: review needed

#587 [엄격 모드] 오타 수정
  1-js/02-first-steps/03-strict-mode/article.md
Labels: review needed
