Repository javascript-tutorial/ko.javascript.info, pull requests merged in 2020-07, with the labels that each got.

#559 [폼 프로퍼티와 메서드] 본문 번역
  2-ui/4-forms-controls/1-form-elements/article.md
Labels: changes requested, under review

#570 [CSS 애니메이션] 해답 번역
  7-animation/2-css-animations/2-animate-logo-bezier-css/solution.md
Labels: changes requested

#596 [숫자형] 오타 수정
  1-js/05-data-types/02-number/article.md
Labels: review needed

#592 [정규식 앵커] 본문 및 과제 번역
  9-regular-expressions/04-regexp-anchors/1-start-end/solution.md
  9-regular-expressions/04-regexp-anchors/1-start-end/task.md
  9-regular-expressions/04-regexp-anchors/article.md
Labels: review needed

#600 [setTimeout과 setInterval을 이용한 호출 스케줄링] 불완전한 문장 수정
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
Labels: review needed

#603 [문서 수정하기] 번역 오류 수정 #533
  2-ui/1-document/07-modifying-document/article.md
Labels: review needed

#608 [문자열] 오타 수정, 보완
  1-js/05-data-types/03-string/article.md
Labels: review needed

#612 [자료형] 오타 수정, 원문 업데이트 반영
  1-js/02-first-steps/05-types/article.md
Labels: review needed

#601 기본 연산자와 수학 과제 번역
  1-js/02-first-steps/08-operators/4-fix-prompt/solution.md
  1-js/02-first-steps/08-operators/4-fix-prompt/task.md
Labels: changes requested
