Repository javascript-tutorial/ko.javascript.info, pull requests merged in 2020-08, with the labels that each got.

#622 [논리 연산자 단락평가]오번역 수정 #621
  1-js/02-first-steps/11-logical-operators/article.md
Labels: review needed

#623 [오번역 수정] 배열 in 자료구조와 자료형 #583
  1-js/05-data-types/04-array/article.md
Labels: review needed

#637 [Hello, world!] 어색한 표현 수정 #635
  1-js/02-first-steps/01-hello-world/article.md
Labels: review needed

#626 [구조 분해 할당] - 어색한 표현 수정 #606
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: review needed

#646 [함수] 오타 수정
  1-js/02-first-steps/15-function-basics/article.md
Labels: review needed

#675 [웹 컴포넌트] 인코딩 깨지는 커밋 revert 하고 대단원 제목만 번역
  8-web-components/index.md
Labels: review needed

#647 [숫자형] 오타 수정
  1-js/05-data-types/11-date/3-weekday/task.md
Labels: review needed

#680 깃이슈 템플릿
  .github/ISSUE_TEMPLATE/Bug REPORT.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/개선제안.md
  .github/ISSUE_TEMPLATE/대시보드_권한_요청.md
  .github/ISSUE_TEMPLATE/오번역수정.md
  .github/ISSUE_TEMPLATE/오타수정.md
  .github/ISSUE_TEMPLATE/작업할_내용_공유.md
Labels: review needed

#738 [신규 번역]파트1 객체4.1 Summary 번역누락반영 #737
  1-js/04-object-basics/01-object/article.md
Labels: review needed

#747 [여러 행 모드] 번역
  9-regular-expressions/05-regexp-multiline-mode/article.md
Labels: review needed

#761 [주석 수정] 자료구조와 자료형 - 구조 분해 할당
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: review needed

#764 [CSS animation] 처음부터 transition-delay까지 문단 번역
  7-animation/2-css-animations/article.md
Labels: review needed

#775 [오타수정] 파트1 5.10 구조분해할당 #774
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: review needed

#778 [오타 수정] Part1 4.8 객체를 원시형으로 변환하기 #777
  1-js/04-object-basics/09-object-toprimitive/article.md
Labels: review needed

#785 [오타수정]Part1 6.10 함수 바인딩 #783
  1-js/06-advanced-functions/10-bind/article.md
Labels: review needed

#790 [오번역 수정] - 용량단위 수정 #789
  6-data-storage/01-cookie/article.md
Labels: review needed

#796 [오타수정]Part1 7.2 프로퍼티 getter와 setter #795
  1-js/07-object-properties/02-property-accessors/article.md
Labels: review needed

#797 [오타수정]파트1 4.7심볼형 오타수정 #793
  1-js/04-object-basics/08-symbol/article.md
Labels: needs +1

#800 [오타수정] 파트 1 - 9.2 클래스 상속
  1-js/09-classes/02-class-inheritance/article.md
Labels: review needed

#773 [어색한 표현 수정] 파트1 5.3 문자열 #772
  1-js/05-data-types/03-string/article.md
Labels: review needed

#788 [오타수정] Part1 7.1 프로퍼티 플래그와 설명자 #787
  1-js/07-object-properties/01-property-descriptors/article.md
Labels: changes requested

#768 [문서 수정하기] 누락부분 번역
  2-ui/1-document/07-modifying-document/article.md
Labels: review needed

#804 [오번역수정] Part3 5.1 베지어곡선 수정 #802
  7-animation/1-bezier-curve/article.md
Labels: review needed

#806 [오타수정] Part1 8.2 함수의 prototype 프로퍼티 #805
  1-js/08-prototypes/02-function-prototype/article.md
Labels: review needed

#810 [오타수정] Part1 9.2 클래스 상속 #809
  1-js/09-classes/02-class-inheritance/article.md
Labels: review needed

#815 [오번역 수정] Part1 5.10 구조분해할당 과제 #813
  1-js/05-data-types/10-destructuring-assignment/6-max-salary/task.md
Labels: review needed

#776 [번역] Part1 5.6 iterable 객체 누락된 부분 번역 #756
  1-js/05-data-types/06-iterable/article.md
Labels: changes requested
