Repository javascript-tutorial/ko.javascript.info, pull requests merged in 2020-09, with the labels that each got.

#825 [오번역 수정] 네이티브 프로토타입 - #824
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: review needed

#818 [번역] Part1 변수와 상수 warn 부분
  1-js/02-first-steps/04-variables/article.md
Labels: review needed

#741 [신규 번역]파트2 4.3이벤트 원문번역 #641
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/solution.view/index.html
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/source.view/index.html
  2-ui/4-forms-controls/3-events-change-input/article.md
Labels: review needed

#834 [오타 수정] 파트 1 - 11.2 프라미스
  1-js/11-async/02-promise-basics/article.md
Labels: review needed

#823 [어색한 표현 수정] Part1 9.5 내장 클래스 확장하기
  1-js/09-classes/05-extend-natives/article.md
Labels: review needed

#811 [번역] Part1 9.1 클래스와 기본 문법 미번역된 부분 번역 #807
  1-js/09-classes/01-class/article.md
Labels: review needed

#710 [기초 문법 요약] - 오번역 수정 #709
  1-js/02-first-steps/18-javascript-specials/article.md
Labels: changes requested

#728 [1.6.10 함수 바인딩] 과제&해답 번역
  1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/solution.md
  1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/task.md
  1-js/06-advanced-functions/10-bind/3-second-bind/solution.md
  1-js/06-advanced-functions/10-bind/3-second-bind/task.md
  1-js/06-advanced-functions/10-bind/4-function-property-after-bind/solution.md
  1-js/06-advanced-functions/10-bind/4-function-property-after-bind/task.md
  1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
  1-js/06-advanced-functions/10-bind/5-question-use-bind/task.md
  1-js/06-advanced-functions/10-bind/6-ask-partial/solution.md
  1-js/06-advanced-functions/10-bind/6-ask-partial/task.md
Labels: review needed

#697 [객체] - Object with const can be changed 번역 #696
  1-js/04-object-basics/01-object/article.md
Labels: review needed

#845 [오번역수정] 11.2 프라미스 #844
  1-js/11-async/02-promise-basics/article.md
Labels: review needed

#841 [오타 수정]8.2 함수의 prototype 프로퍼티 #840
  1-js/08-prototypes/02-function-prototype/1-changing-prototype/task.md
Labels: review needed

#814 Part1 9.2 클래스 상속 미번역된 부분 번역
  1-js/09-classes/02-class-inheritance/article.md
Labels: changes requested

#745 [과제번역] Part 1. 5.2 number: task1, solution1, task2, solution2
  1-js/05-data-types/02-number/1-sum-interface/solution.md
  1-js/05-data-types/02-number/1-sum-interface/task.md
  1-js/05-data-types/02-number/2-why-rounded-down/solution.md
  1-js/05-data-types/02-number/2-why-rounded-down/task.md
  1-js/05-data-types/02-number/3-repeat-until-number/solution.md
  1-js/05-data-types/02-number/3-repeat-until-number/task.md
Labels: review needed

#859 [오타 수정] 파트 1 - 12.1 과제 의사 난수 생성기
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/task.md
Labels: review needed

#746 [과제번역] Part2. 2.4 Browser default actions 과제 번역 #711
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/solution.md
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/task.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/solution.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/task.md
Labels: review needed

#760 [Date 객체와 날짜] - 미번역분 번역 #759
  1-js/05-data-types/11-date/article.md
Labels: review needed

#862 #861 [개선제안] CONTRIBUTING.md 초안 작성 및 README.md 수정
  CONTRIBUTING.md
  README.md
Labels: needs +1

#657 [기초 문법 요약] 오타 수정 #656
  1-js/02-first-steps/18-javascript-specials/article.md
Labels: changes requested

#851 [오번역수정] 3.5 테스트 자동화와 Mocha 과제 솔루션 #850
  1-js/03-code-quality/05-testing-mocha/3-pow-test-wrong/solution.md
Labels: review needed

#849 [오번역수정] 네이티브 프로토타입 #848
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: review needed

#847 [오번역수정] 5.5 배열과 메서드 #846
  1-js/05-data-types/05-array-methods/article.md
Labels: review needed

#843 [오번역수정] 5.3 문자열 #842
  1-js/05-data-types/03-string/article.md
Labels: review needed

#682 [fetch] - 과제 번역 #679
  5-network/01-fetch/01-fetch-users/_js.view/source.js
  5-network/01-fetch/01-fetch-users/_js.view/test.js
  5-network/01-fetch/01-fetch-users/solution.md
  5-network/01-fetch/01-fetch-users/task.md
Labels: review needed
