Repository javascript-tutorial/ko.javascript.info, pull requests merged in 2022-10, with the labels that each got.

#1565 [오타수정] Part 1 4.3 가비지 컬렉션 #1564
  1-js/04-object-basics/03-garbage-collection/article.md
Labels: review needed

#1567 [오타수정] Part1 9.2 클래스 상속
  1-js/09-classes/02-class-inheritance/article.md
Labels: review needed

#1572 [오번역수정] Part 1 - 2.15 함수 #1571
  1-js/02-first-steps/15-function-basics/article.md
Labels: review needed

#1574 [오타수정] Part 1 - 2.5 자료형 (#1569)
  1-js/02-first-steps/05-types/article.md
Labels: review needed

#1575 [오타수정] Part 1 - 2.7 형 변환 (#1573)
  1-js/02-first-steps/07-type-conversions/article.md
Labels: review needed

#1576 [오번역수정] Part 1. 5-6 iterable 객체 이터러블과 유사 배열 #1563
  1-js/05-data-types/06-iterable/article.md
Labels: review needed

#1580 [오타수정] Part2 3.3 드래그 앤 드롭과 마우스 이벤트(#1579)
  2-ui/3-event-details/4-mouse-drag-and-drop/article.md
Labels: review needed

#1585 [오타수정] Part 2 5.1 DOMContentLoaded, load, beforeunload, unload 이벤트 #1584
  2-ui/5-loading/01-onload-ondomcontentloaded/article.md
Labels: review needed

#1590 [오타수정] Part1 2.17 화살표 함수 기본 과제 해답 (#1524)
  1-js/02-first-steps/17-arrow-functions-basics/1-rewrite-arrow/solution.md
Labels: review needed

#1594 [오타수정] Part1 13.1 모듈 소개(#1593)
  1-js/13-modules/01-modules-intro/article.md
Labels: review needed

#1540 [신규 번역] Part 2 - 2.1 브라우저 이벤트 소개 과제 1-3 번역 (#1539)
  2-ui/2-events/01-introduction-browser-events/01-hide-other/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/01-hide-other/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/01-hide-other/task.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/solution.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/task.md
  2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/solution.md
  2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/task.md
Labels: review needed

#1477 fix: [오번역수정] Part 1 - 2.15 [함수] 매개변수 설명 수정 요청 (issue #1444)
  1-js/02-first-steps/15-function-basics/article.md
Labels: enhancement, review needed

#1536 [신규 번역] Part 2. 2.9 Element size and scrolling 마지막 과제
  2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/solution.md
  2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/task.md
Labels: review needed

#1604 [오타수정] Part2 1.5 주요 노드 프로퍼티 과제(Count descendants)의 문제 번역 (#1068)
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/task.md
Labels: review needed

#1607 [웹소켓] 이미지 번역(#1606)
  5-network/11-websocket/websocket-handshake.svg
Labels: review needed

#1608 [웹소켓] 기존 번역 보완 - line112 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1610 [웹소켓] 번역 - line193 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1612 [웹소켓] 기존 번역 보완 - line202 (#1616)
  5-network/11-websocket/article.md
Labels: review needed

#1613 [웹소켓] 기존 번역 보완 - line172 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1615 [웹소켓] 번역 - line241 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1617 [웹소켓]번역-line-291(#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1618 [웹소켓] 번역 - line294 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1623 [웹소켓] 번역 - line269 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1626 [웹소켓] 번역 - line278 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1629 [웹소켓] 번역 - line271 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1627 [웹소켓] 번역 - line274 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1628 [웹소켓] 번역 - line238 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1620 [웹소켓] 번역 - line233 (#1606)
  5-network/11-websocket/article.md
Labels: changes requested

#1631 [웹소켓] 번역 - line281 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1616 [웹소켓] 번역 - line252 (#1606)
  5-network/11-websocket/article.md
Labels: changes requested

#1632 [웹소켓] 번역 - line255 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1636 [웹소켓] 번역 - line250 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1633 [웹소켓] 번역 - line245 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1643 [웹소켓] 번역 - line247 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1646 [웹소켓] 번역 - line276 (#1606)
  5-network/11-websocket/article.md
Labels: review needed

#1644 [웹소켓] 번역 - line270 (#1606)
  5-network/11-websocket/article.md
Labels: review needed
