Repository javascript-tutorial/ko.javascript.info, pull requests merged in 2023-12, with the labels that each got.

#1727 #1724 random min max 과제 번역11번째줄
  1-js/05-data-types/02-number/8-random-min-max/task.md
Labels: needs +1

#1725 [신규번역] random-min-max 해답 번역 3번째줄 번역 #1723
  1-js/05-data-types/02-number/8-random-min-max/solution.md
Labels: review needed

#1728 #1718 random-min-max 과제 번역 첫번째줄
  1-js/05-data-types/02-number/8-random-min-max/task.md
Labels: changes requested

#1730 random-min-max 과제 문제 번역 세번째 줄(#1719)
  1-js/05-data-types/02-number/8-random-min-max/task.md
Labels: review needed, needs +1

#1709 [오타수정] Part1 9.4 private, protected 프로퍼티와 메서드#1708
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: review needed

#1729 #1717 random-min-max solution 번역 5번째 줄
  1-js/05-data-types/02-number/8-random-min-max/solution.md
Labels: review needed, needs +1

#1733 #1721 random-min-max 과제 번역 두번째 줄
  1-js/05-data-types/02-number/8-random-min-max/task.md
Labels: changes requested
